### ISSUE TITLE
error: Could not find a declaration file for module '@taxi/input'.

### ISSUE THREAD

**Issue by rmros** [serhii-havrylenko/monorepo-babel-ts-lerna-starter#1]
src/LoginForm.tsx(1,23): error TS7016: Could not find a declaration file for module '@taxi/input'. '/home/ramin/Desktop/project/saas-model/backend/packages/input/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/taxi__input` if it exists or add a new declaration (.d.ts) file containing `declare module '@taxi/input';

**Comment by ggascoigne** [comment]
You don't say what command you were running to get that error, but I'm going to guess that it was on the initial build.  If that's the case, try running `yarn build:declarations` once before the initial build.

**Comment by rmros** [comment]
@ggascoigne  yes, thanks :)
