### ISSUE TITLE
How to add static files in final build?

### ISSUE THREAD

**Issue by adyVue** [serhii-havrylenko/monorepo-babel-ts-lerna-starter#3]
Hi, 
Thanks for sharing this really nice content, it really helped me in getting started.
I would like to know what other changes do I need to make in order to get the static file in the final `dist` folder ?
In dev mode I am serving the image/icon from public folder in root but running build command does nothing to static files.

**Comment by serhii-havrylenko** [comment]
Hi @adyVue, I'm happy to hear that this repo was helpful. Regarding serving static files it actually depends on your use case. For instance you could create separate build command for specific package which would copy files as well or create `postbuild` script which runs bash/js script and copies listed files (or using glob).
